apiVersion: v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLables:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app
          image: kammana/pyappeks:v1
          ports:
            - containerPort: 8080
