apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: first-application-myapp:apps/Deployment:default/my-app
  name: my-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLables:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: kammana/pyappeks:v1
          name: my-app
          ports:
            - containerPort: 8080
